apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xsi4o49z1-go
  janus-idp.io/tekton: xsi4o49z1-go
  backstage.io/kubernetes-id: xsi4o49z1-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xsi4o49z1-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
